notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t pisces .
 - docker images | grep -c pisces
 - echo 'Verify program(s) from this repo'
 - docker run -it pisces dotnet /opt/wsi-t113/bin/Pisces.dll -h
